### ISSUE TITLE
Clarification for series of text annotations

### ISSUE THREAD

**Issue by manikanta29788** [vedavaapi/ullekhanam-ui#10]
Hi Vishwas,

My initial understanding with respect to text annotation was that for every image annotation there will be only one text annotation, but in our last recent call you mentioned that there will be series of text annotations. This sounds fine, but need some clarifications.

1) On click of image annotation should we have to show(both in text area below image annotation and text area below page image) all the text annotations of the clicked image annotation?
2) If point 1 is YES then how we need to update the text annotations ?
3) If point 1 is NO then which among the series of text annotations need to be displayed on the text areas accordingly?

**Comment by vvasuki** [comment]
namaste maNi - Please report future issues in https://github.com/vedavaapi/ullekhanam-ui-v1/issues instead since that's where the kimshuka UI code is located. 

Answering inline:

> My initial understanding with respect to text annotation was that for every image annotation there will be only one text annotation, but in our last recent call you mentioned that there will be series of text annotations.

Yes - albeit - cases with multiple text annotations will be rare.

> On click of image annotation should we have to show(both in text area below image annotation and text area below page image) all the text annotations of the clicked image annotation?

In the text area below the image annotation, show only one text annotation. Pick one according to the following rules applied sequentially:

- If one of the text annotations is "verified" (ie- has a ValidationAnnotation pointing to it, which can be detected using the targets API) by an admin, use it.
- If one of the text annotations is "verified" (ie- has a ValidationAnnotation pointing to it, which can be detected using the targets API) by some non-admin, use it.
- Else, just pick any one text annotation (the first for example).

In the text area below the page image, show all available text annotations.

> If point 1 is YES then how we need to update the text annotations ?

Firstly, if the annotation has editable_by_others = False (<-- unlikely, rare case) and the annotation source is some other user, that annotation cannot be edited by the user unless he is an admin (which can be determined using the current_user api). In such a non-admin case, let the user create a new text annotation associated with the image annotation.

Otherwise, just let him edit whatever TextAnnotation is shown in the text area below the ImageAnnotation.

Please don't hesitate to reopen this issue if you have further questions!

**Comment by manikanta29788** [comment]
how to update the text annotation, what is the object that we need to pass in the payload for updating the text annotation??

**Comment by vvasuki** [comment]
> how to update the text annotation, what is the object that we need to pass in the payload for updating the text annotation??

Just use the same https://api.vedavaapi.org/py/ullekhanam/docs#!/default/post_entity_list_handler API. Make sure that content._id field is filled appropriately so that the backend knows which Annotation is to be updated.

> Do let us know if any modification required in update or delete text annotation flow.

That's a great idea - sounds fine! Be warned though that the backend will reject any unauthorized edits (as explained in the previous message).
